# Generated by Django 5.0.6 on 2024-09-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_userdatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralBtcDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_address', models.CharField(max_length=42, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralEthDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth_address', models.CharField(max_length=42, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralLtcDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltc_address', models.CharField(max_length=42, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSolDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_address', models.CharField(max_length=42, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralUsdtDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt_address', models.CharField(max_length=42, null=True)),
            ],
        ),
    ]
