# Generated by Django 5.0.6 on 2024-09-25 03:19

import dash.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_btcdeposit_ethdeposit_ltcdeposit_soldeposit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BtcPayout',
            fields=[
                ('id', models.CharField(default=dash.models.generate_deposit_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('method_of_crypto', models.CharField(default='BTC', max_length=20)),
                ('btc_deposit', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EthPayout',
            fields=[
                ('id', models.CharField(default=dash.models.generate_deposit_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('method_of_crypto', models.CharField(default='ETH', max_length=20)),
                ('eth_deposit', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LtcPayout',
            fields=[
                ('id', models.CharField(default=dash.models.generate_deposit_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('method_of_crypto', models.CharField(default='LTC', max_length=20)),
                ('ltc_deposit', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolPayout',
            fields=[
                ('id', models.CharField(default=dash.models.generate_deposit_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('method_of_crypto', models.CharField(default='SOL', max_length=20)),
                ('sol_deposit', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsdtPayout',
            fields=[
                ('id', models.CharField(default=dash.models.generate_deposit_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('method_of_crypto', models.CharField(default='USDT', max_length=20)),
                ('usdt_deposit', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
