# Generated by Django 5.0.6 on 2024-09-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_btcpayout_ethpayout_ltcpayout_solpayout_usdtpayout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btcpayout',
            old_name='btc_deposit',
            new_name='btc_payout',
        ),
        migrations.RenameField(
            model_name='ethpayout',
            old_name='eth_deposit',
            new_name='eth_payout',
        ),
        migrations.RenameField(
            model_name='ltcpayout',
            old_name='ltc_deposit',
            new_name='ltc_payout',
        ),
        migrations.RenameField(
            model_name='solpayout',
            old_name='sol_deposit',
            new_name='sol_payout',
        ),
        migrations.RenameField(
            model_name='usdtpayout',
            old_name='usdt_deposit',
            new_name='usdt_payout',
        ),
    ]
