# Generated by Django 5.0.6 on 2024-09-26 02:21

import dash.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_rename_btc_deposit_btcpayout_btc_payout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTrader',
            fields=[
                ('id', models.CharField(default=dash.models.generate_deposit_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('profile_image', models.ImageField(upload_to='images/')),
                ('trader_name', models.CharField(default='New Trader', max_length=255)),
                ('profit_share', models.CharField(default='20', max_length=255)),
                ('category', models.CharField(default='Crypto', max_length=255)),
                ('wins', models.IntegerField(null=True)),
                ('losses', models.IntegerField(null=True)),
                ('copiers', models.IntegerField(default=45)),
                ('copy_max', models.IntegerField(null=True)),
                ('minimum_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(default='NEUTRAL', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset', models.CharField(default='BTC/USDT', max_length=50)),
                ('leverage', models.IntegerField(null=True)),
                ('change', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('trader_key', models.ForeignKey(default='BD-64EFE4', on_delete=django.db.models.deletion.SET_DEFAULT, to='dash.newtrader')),
            ],
        ),
    ]
