# Generated by Django 5.0.6 on 2024-09-26 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_newtrader_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='trader',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dash.newtrader'),
        ),
    ]
