# Generated by Django 5.0.6 on 2024-09-26 11:26

import dash.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_userdatabase_trader'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPlan',
            fields=[
                ('id', models.CharField(default=dash.models.generate_deposit_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('bot_plan', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('enterprise', 'Enterprise'), ('gold', 'Gold')], default='gold', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trades',
            name='trader_key',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dash.newtrader'),
        ),
        migrations.CreateModel(
            name='BotTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bot_key', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dash.botplan')),
            ],
        ),
    ]
