# Generated by Django 5.0.6 on 2024-09-26 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_botplan_alter_trades_trader_key_bottrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botplan',
            name='bot_plan',
        ),
        migrations.AddField(
            model_name='botplan',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='bot_plans',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('enterprise', 'Enterprise')], default=None, max_length=10, null=True),
        ),
    ]
