# Generated by Django 5.0.6 on 2024-09-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_alter_userdatabase_btc_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabase',
            name='btc_address',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='eth_address',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='ltc_address',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='sol_address',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='usdt_address',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
    ]
