# Generated by Django 5.0.6 on 2024-09-27 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_alter_userdatabase_btc_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottrade',
            old_name='bot_key',
            new_name='bot_plan',
        ),
        migrations.AddField(
            model_name='bottrade',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.userdatabase'),
        ),
    ]
