# Generated by Django 5.0.6 on 2024-09-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_remove_bottrade_bot_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottrade',
            name='asset',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
