# Generated by Django 5.0.6 on 2024-09-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0015_bottrade_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=255, null=True)),
                ('phone', models.CharField(default=None, max_length=255, null=True)),
                ('message', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
