# Generated by Django 5.0.6 on 2024-10-01 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0018_rename_customuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
