# Generated by Django 5.0.6 on 2024-10-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0019_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=255, null=True)),
                ('lastname', models.CharField(default=None, max_length=255, null=True)),
                ('password', models.CharField(default=None, max_length=255, null=True)),
                ('country', models.CharField(default=None, max_length=255, null=True)),
                ('currency', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
