# Generated by Django 5.0.6 on 2024-10-03 01:00

import dash.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0021_extenduser_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='account_name',
            field=models.CharField(default='New User', help_text='The name on your bank account', max_length=255),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='account_number',
            field=models.CharField(default='00000000', help_text='Your bank account number', max_length=20),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='bank_name',
            field=models.CharField(default='Federal Bank (default)', help_text='Your house address', max_length=255),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='lusd_address',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='routing_number',
            field=models.CharField(default='00000000', help_text='Your bank routing number', max_length=20),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='usdc_address',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.CreateModel(
            name='BankPayout',
            fields=[
                ('id', models.CharField(default=dash.models.generate_deposit_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('method_of_payment', models.CharField(default='Bank', max_length=20)),
                ('bank_deposit', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LusdPayout',
            fields=[
                ('id', models.CharField(default=dash.models.generate_deposit_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('method_of_crypto', models.CharField(default='LUSD', max_length=20)),
                ('eth_payout', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsdcPayout',
            fields=[
                ('id', models.CharField(default=dash.models.generate_deposit_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('method_of_crypto', models.CharField(default='USDC', max_length=20)),
                ('eth_payout', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
