# Generated by Django 5.0.6 on 2024-10-03 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0022_userdatabase_account_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankpayout',
            old_name='bank_deposit',
            new_name='bank_payout',
        ),
    ]
