# Generated by Django 5.0.6 on 2024-10-03 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0023_rename_bank_deposit_bankpayout_bank_payout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lusdpayout',
            old_name='eth_payout',
            new_name='lusd_payout',
        ),
        migrations.RenameField(
            model_name='usdcpayout',
            old_name='eth_payout',
            new_name='usdc_payout',
        ),
    ]
