# Generated by Django 5.0.6 on 2024-10-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0024_rename_eth_payout_lusdpayout_lusd_payout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatabase',
            name='trader',
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='trader',
            field=models.ManyToManyField(blank=True, to='dash.newtrader'),
        ),
    ]
