# Generated by Django 5.0.6 on 2024-10-04 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0025_remove_userdatabase_trader_userdatabase_trader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatabase',
            name='trader',
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='trader',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dash.newtrader'),
        ),
    ]
