from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('about/', views.about),
    path('signup/', views.signup),
    path('signin/', views.signin),
    path('otp/',  views.otp_page),
    path('signout/', views.signout),
    path('dashboard/', views.dashboard, name='dashboard_url'),
    path('accountsettings/', views.account_settings),
    path('wallet/', views.wallet),
    path('fund/', views.fund),
    path('withdraw/', views.withdraw),
    path('market/', views.market),
    path('crypto/', views.crypto),
    path('news/', views.news),
    path('news/<str:news_id>/', views.news_detail, name='blog'),
    path('administrator/settings/', views.administrator_settings),
    path('fund/', views.fund),
    path('current-plans/', views.current_plans),
    path('administrator/deposit/', views.administrator_deposit),
    path('administrator/withdraw/', views.administrator_payout),
    path('administrator/traders/', views.administrator_traders),
    path('traders/<str:trader_id>/delete/', views.delete_trader, name='delete_trader'),
    path('traders/<str:trader_id>/', views.traders_manager, name='traders_manager'),
    path('administrator/trades/', views.trades),
    path('administrator/complete_trade/', views.complete_trade),
    path('administrator/dashboard/', views.administrator_dashboard),
    path('trade/', views.trade, name='trade'),
    path('trader-profile/<str:trader_id>/', views.trader_profile, name='trader_profile'),
    path('bot_plan/', views.bot_plan),
    path('bot_payment/', views.bot_payment),
    path('transfer/', views.transfer),
    path('administrator/bot-trade/', views.bot_trades),
    path('administrator/completebot/', views.complete_bot),
    path('administrator/login/', views.administrator_signin),
    path('forgot-pass/', views.forgot_pass),

]